// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBD7HlzW0P-0AcjHmKPy7_SlGAq7_gbAmE',
    appId: '1:908225876428:web:31fdf07aad976a2f8a4d69',
    messagingSenderId: '908225876428',
    projectId: 'my-store-a9846',
    authDomain: 'my-store-a9846.firebaseapp.com',
    storageBucket: 'my-store-a9846.firebasestorage.app',
    measurementId: 'G-QRZT0E5RMC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCliqobxQs_0YVwKxD4NtsdwnClg1ytfng',
    appId: '1:908225876428:android:c19a5671cd8197588a4d69',
    messagingSenderId: '908225876428',
    projectId: 'my-store-a9846',
    storageBucket: 'my-store-a9846.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9lFKxYvLz_SOOAC0DXXxMEgte8XPRZ6k',
    appId: '1:908225876428:ios:e8ab999ec90bf0298a4d69',
    messagingSenderId: '908225876428',
    projectId: 'my-store-a9846',
    storageBucket: 'my-store-a9846.firebasestorage.app',
    iosBundleId: 'com.example.myStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9lFKxYvLz_SOOAC0DXXxMEgte8XPRZ6k',
    appId: '1:908225876428:ios:e8ab999ec90bf0298a4d69',
    messagingSenderId: '908225876428',
    projectId: 'my-store-a9846',
    storageBucket: 'my-store-a9846.firebasestorage.app',
    iosBundleId: 'com.example.myStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBD7HlzW0P-0AcjHmKPy7_SlGAq7_gbAmE',
    appId: '1:908225876428:web:812170925dffdbcf8a4d69',
    messagingSenderId: '908225876428',
    projectId: 'my-store-a9846',
    authDomain: 'my-store-a9846.firebaseapp.com',
    storageBucket: 'my-store-a9846.firebasestorage.app',
    measurementId: 'G-8D8ZHJTL9J',
  );
}
